# Don't print a new line at the start of the prompt
add_newline = false

prompt_order = [
    "username",
#    "hostname",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "nodejs",
    "character"
]

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
symbol = "â¯"     # The "symbol" segment is being set to "âœ"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false
symbol = "ğŸ“¦  "

[directory]
truncation_length = 2

[hostname]
ssh_only = false
prefix = ""
suffix = ""
trim_at = ".companyname.com"
disabled = false

[username]
disabled = false
show_always = true

[time]
disabled = false
format = "[ %T ]"
utc_time_offset = -3

[line_break]
disabled = false